version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./conf:/etc/prometheus/conf
      - ./prometheus:/prometheus
      - /etc/ssl/very-secure-secrets/k3s-startupnation-cluster/:/etc/ssl/very-secure-secrets/k3s-startupnation-cluster/
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/conf/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.enable-admin-api
    networks:
      - traefik
    labels:
      - traefik.enable=false

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./conf:/etc/prometheus/conf
    ports:
      - "9093:9093"
    command:
      - --config.file=/etc/prometheus/conf/alertmanager.yml
    env_file:
      - .env
    networks:
      - traefik
    labels:
      - traefik.enable=false

networks:
  traefik:
    external: true
